[theme]
theme = "nord-dark"
[icons]
icons = "awesome5"
[[block]]
block = "cpu"
interval = 1
[[block]]
block = "disk_space"
path = "/home/poss/"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = "$icon poss: $available.eng(w:2)"
[[block]]
block = "memory"
format = "$icon $mem_used.eng(prefix:Mi)/$mem_total.eng(prefix:Mi)[$mem_used_percents.eng(w:2)]"
[[block]]
block = "temperature"
format = " $icon $max "
format_alt = " $icon $min min, $max max, $average avg "
interval = 10
chip = "*-isa-*"
[[block]]
block = "sound"
[[block.click]]
button = "left"
cmd = "pavucontrol"
[[block]]
block = "net"
[[block]]
block = "battery"
format = " $icon $percentage "
[[block]]
block = "bluetooth"
mac = "00:18:09:92:1B:BA"
[[block]]
block = "time"
interval = 5
format = "$icon $timestamp.datetime(f:'%a %Y/%m/%d %R')"
[[block]]
block = "backlight"


